// File generated by Blink v0.15.1 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const ReadyPacket: {
	On: (Listener: (Player: Player, Value: void) => void) => (() => void)
}
export declare const ClientToServer: {
	On: (Listener: (Player: Player, Value: { cframe: CFrame }) => void) => (() => void)
}
export declare const ServerToClient: {
	Fire: (Player: Player, Value: { player: Player, cframe: CFrame }) => void
	FireAll: (Value: { player: Player, cframe: CFrame }) => void
	FireExcept: (Except: Player, Value: { player: Player, cframe: CFrame }) => void
	FireList: (List: Player[], Value: { player: Player, cframe: CFrame }) => void
}
