// File generated by Blink v0.14.15 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const Test: {
	Fire: (Player: Player, Value: void) => void
	FireAll: (Value: void) => void
	FireExcept: (Except: Player, Value: void) => void
	FireList: (List: Player[], Value: void) => void
}
