// File generated by Blink v0.15.1 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const ReadyPacket: {
	Fire: (Value: void) => void
}
export declare const ClientToServer: {
	Fire: (Value: { cframe: CFrame, deltaTime: number }) => void
}
export declare const ServerToClient: {
	On: (Listener: (Value: { player: Player, cframe: CFrame, deltaTime: number }) => void) => (() => void)
}
