// File generated by Blink v0.14.15 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
export declare const Test: {
	On: (Listener: (Value: void) => void) => (() => void)
}
